# Generated by Django 3.2.7 on 2021-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_category_cat_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_items',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.Listing'),
        ),
    ]
