# Generated by Django 3.2.7 on 2021-09-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comments_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
