# Generated by Django 3.2.7 on 2021-09-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comments_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageurl',
            field=models.URLField(max_length=1000),
        ),
    ]
